### ISSUE TITLE
BScreen显示异常

### ISSUE THREAD

**Issue by BevisZhang-it** [smartloli/kafka-eagle#404]
![image](https://user-images.githubusercontent.com/51435883/91685719-b81c4d00-eb8d-11ea-91e1-1c5f310ddea1.png)
![image](https://user-images.githubusercontent.com/51435883/91685745-cec2a400-eb8d-11ea-8994-6dac7636a1fc.png)

**Comment by FrommyMind** [comment]
I have the same issue, I think this is because the topicProducerLogSizeStats function in [TopicRankSubTask.java](https://github.com/smartloli/kafka-eagle/blob/master/kafka-eagle-web/src/main/java/org/smartloli/kafka/eagle/web/quartz/TopicRankSubTask.java)
sometime the code `topicLogSize.setDiffval(logsize - lastTopicLogSize.getLogsize());` may got negative result. 

Thus, in the table ke_logsize , the value of  `diffval` column had some negative values.

**Comment by 812406210** [comment]
你好，我这边部署了，但是bscreen的数据显示跟你的刚好相反，你的有我的没有，我的有你的没有，请问下你是怎么配置的，consumer有数据呀
